version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: prompt-lab-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prompt-lab-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prompt-lab-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
  backend_data:

networks:
  default:
    name: prompt-lab-network
