version: '3.8'

services:
  # Backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=true
      - RELOAD=true
    env_file:
      - .env
    command: uvicorn app.adapters.web.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - RELOAD=true
    env_file:
      - .env
    command: bun run dev
